=== InnovaLangues/catarina/datas/catarina.dtd
<?xml version='1.0' encoding="UTF-8"?>

<!ELEMENT catarina (ressource)* >

<!ELEMENT ressource (type* , profil* , langue* , activite_langagiere*)>
	<!ATTLIST ressource 
		nom CDATA #IMPLIED
		description CDATA #IMPLIED
		url CDATA #IMPLIED
		auteur CDATA #IMPLIED
		version CDATA #IMPLIED			
		repertoire (Oui|Non) #IMPLIED
		ressource_fonctionnement CDATA #IMPLIED	
		ressource_analogue CDATA #IMPLIED		
	>
<!ELEMENT type EMPTY>
	<!ATTLIST type
		nom CDATA #IMPLIED
	>
	
<!ELEMENT profil EMPTY>
	<!ATTLIST profil
		nom CDATA #IMPLIED
	>

<!ELEMENT langue EMPTY>
	<!ATTLIST langue
		nom CDATA #IMPLIED
	>

<!ELEMENT activite_langagiere EMPTY>
	<!ATTLIST activite_langagiere
		nom CDATA #IMPLIED
	>

=== InnovaLangues/catarina/datas/liste_modele.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE catarina SYSTEM "catarina.dtd">

<catarina>
<!--Outils logiciels facilitant la communication et la collaboration-->
	<ressource nom = "Blogger" description = "Blogger est une plateforme logicielle en ligne gratuite qui facilite la publication d'un blog, gratuit et sans publicité. Un blog est un type de site web – ou une partie d'un site web – utilisé pour la publication périodique et régulière de nouveaux articles, généralement succincts. Il est facile de personnaliser la mise en page, et d'ajouter des photos et textes. Il est également possible pour les utilisateurs de poster des commentaires sur les articles." url = "www.blogger.com" auteur = "Google Inc." version = "2003" repertoire = "Non" ressource_fonctionnement = "Video de présentation en anglais : http://www.youtube.com/watch?v=Nt6zgbIIJhU ; Présentation en anglais http://www.aplanet-project.eu/Resources/ICT_Tools/III_CATEGORY_Blogging.pdf" ressource_analogue = "">
		<type nom = "Plateformes sociales/Blogs" />
		<profil nom = "Apprenant" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
		<langue nom = "arabe, bengali, bulgare, catalan, chinois, croate, tchèque, danois, néerlandais, anglais, philippin, finnois, français, allemand, grec, goujarati, hébreu, hindi, hongrois, indonésien, italien, japonais, kannada, coréen, letton, lituanien, malais, malayalam, marathi, norvégien, oriya, persan, polonais, portugais, roumain, russe, serbe, slovaque, slovène, espagnol, suédois, tamoul, télougou, thaï, turc, ukrainien, vietnamien" />
		<activite_langagiere nom = "Production écrite"/> 
	</ressource>	
	<ressource nom = "Edublog" description = "Plateforme (en anglais) de création de blog à des fins éducatifs. Avec de nombreuses fonctions, il reste simple d'utilisation." url = "http://edublogs.org/ " auteur = "Edublog" version = "2013" repertoire = "Non" ressource_fonctionnement = "" ressource_analogue = "">
		<type nom = "Plateformes sociales/Blogs" />
		<profil nom = "Apprenant" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
	</ressource>
	<ressource nom = "Wordpress" description = "WordPress est un système de gestion de contenu libre écrit en PHP, reposant sur une base de données MySQL. WordPress est surtout utilisé comme moteur de blog, mais ses fonctionnalités lui permettent également de gérer n'importe quel site web." url = "http://wordpress.org" auteur = "Automattic" version = "3.5.1 (janvier 2013)" repertoire = "Non" ressource_fonctionnement = "http://fr.wikipedia.org/wiki/WordPress" ressource_analogue = "">
		<type nom = "Plateformes sociales/Blogs" />
		<profil nom = "Apprenant" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
	</ressource>
		<ressource nom = "StudyRoom" description = "Ce site permet de créer une classe virtuelle pour faciliter la création de liens apprenants-enseignants et entre apprenants. Il contient des outils collaboratifs tels qu'un tableau blanc 'en temps réel' (realtime whiteboard), un éditeur de texte, un gestionnaire de documents. Un tableau est également disponible pour poster questions et réponses, pour des travaux de groupes. Un système de points pour récompenser les élèves les plus assidûs est mis en place." url = "http://www.getstudyroom.com/" auteur = "Luma Education" version = "" repertoire = "Non" ressource_fonctionnement = "Les réseaux sociaux : Des outils pédagogiques ? Comment les utiliser en classe... http://spiralconnect.univ-lyon1.fr/" ressource_analogue = " OpenStudy http://openstudy.com/">
		<type nom = "Réseaux sociaux/Educatifs" />
		<profil nom = "Apprenant"/>
		<profil nom = "Enseignant"/>
		<profil nom = "Tuteur" />
	</ressource>
	<ressource nom = "Plateformes e-learning et e-formation" description = "Ce site répertorie plus d'une centaines de plateformes séparées en trois catégories : plateformes open-source, plateformes publiques ou gratuites et plateformes commerciales avec spécification des langues. Elles sont utiles à la Formation Ouverte et A Distance (FOAD)" url = "http://cursus.edu/institutions-formations-ressources/formation/13486/plates-formes-learning-formation-2012/" auteur = "Thot Cursus inc." version = "" repertoire = "Oui" ressource_fonctionnement = "" ressource_analogue = "">
		<type nom = "Réseaux sociaux/Educatifs" />
		<profil nom = "Apprenant" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
	</ressource>
	<ressource nom = "Edmodo" description = "Edmodo (réseau social) est une plateforme pour dialoguer de façon sécuritaire avec des personnes œuvrant dans le domaine de l'éducation. On y retrouve aussi une banque de ressources partagées par des enseignants. Le site permet aux écoles de se créer un réseau privé de communication pour le partage entre enseignants, parents et élèves. L'interface du site est en anglais, mais l'utilisateur du site peut choisir de traduire ce dernier en six langues en cliquant sur les drapeaux dans le bas à droite." url = "https://www.edmodo.com" auteur = "Edmodo" version = "2013" repertoire = "Non" ressource_fonctionnement = "" ressource_analogue = "Nixty http://www.nixty.com/">
		<type nom = "Réseaux sociaux/Educatifs" />
		<profil nom = "Apprenant" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
	</ressource>
		<!--Manque OpenStudy, Twitter et analogues-->
		<!--Changer ressources analogues : StudyRoom (OpenStudy)-->
	<ressource nom = "LiveBinders" description = "LiveBinders est un outil TICE en ligne qui va vous permettre d'organiser et de classer toutes vos ressources numériques dans des classeurs virtuels. Classer mais aussi de partager vos trouvailles avec vos collègues ou avec vos élèves. LiveBinders c'est dont une sorte d'outil de curation, un classeur virtuel dans lequel vous allez glisser des docs numériques quel que soit leur format : pages web, PDF, Document texte, images, ou vidéos. Tout est classé à l'ntéeur avec un système d'onglets (des intercalaires virtuels). Vous pouvez même créer des sous intercalaires dans un même onglet pour plus de clarté." url = "http://www.livebinders.com/" auteur = "LiveBinders, Inc." version = "2006-2013" repertoire = "Non" ressource_fonctionnement = "Intérets : http://outilstice.com/2013/01/livebinders-des-classeurs-virtuels-dans-les-nuages/" ressource_analogue = "EduClipper https://educlipper.net/ ; Delicious http://www.symbaloo.com/ ; Symbaloo http://www.symbaloo.com/ ; Evernote http://evernote.com/intl/fr/">
		<type nom = "Diffusion/Plateforme de curation" />
		<profil nom = "Enseignant"/>
		<profil nom = "Concepteur"/>
		<profil nom = "Tuteur"/>
		<profil nom = "Gestionnaire" />
	</ressource>
	<ressource nom = "Pearltrees" description = "Pearltrees est un service gratuit qui permet à chacun d'organiser et partager ce qu'il aime dans internet. Suivant la logique du content curation (faire ressortir le meilleur contenu du web), ce moteur de recherche communautaire repose sur l'idée que la multiplication des contenus de natures diverses (blogs, vidéos postées, twitts, etc.) rend nécessaire une organisation nouvelle d'internet, d'inspiration plus sémantique. Le réseau d'utilisateurs de Pearltrees s'étend aujourd'hui à de nombreux pays" url = "http://www.pearltrees.com/" auteur = "Patrice Lamothe" version = "2009-2013" repertoire = "Non" ressource_fonctionnement = "" ressource_analogue = "Scoop.it! http://www.scoop.it/ ; BagTheWeb http://www.bagtheweb.com/">
		<type nom = "Diffusion/Plateforme de curation" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
	</ressource>
	<ressource nom = "Diigo" description = "Diigo est un très bon service en ligne qui permet de stocker et de partager facilement vos favoris. Après avoir créé votre compte (gratuit), vous pouvez sauvegarder une page web entière, seulement un extrait, une image, une vidéo ou en faire une capture d'écran, surligner un passage, ajouter des annotations et des tags, créer une liste d'articles sur un sujet donné et le publier sous forme de slideshow autonome et interactif (fonction WebSlide). Vous pouvez partager (ou non en mode privé) vos découvertes avec la communauté Diigo, par mail, sur Twitter ou sur un blog (Blogger, WordPress, etc) et plus encore. Même si ce service est en anglais, il est assez facile à prendre en main et s'avère être un bon outil de veille pour collecter des informations qu'on pourra se resservir par la suite." url = "https://www.diigo.com/" auteur = "Diigo Inc" version = "2012" repertoire = "Non" ressource_fonctionnement = "Tutoriels vidéos : http://bibliolab.fr/cms/content/comment-fonctionne-diigo ; Evolution de Delicious en Diigo : http://cursus.edu/article/9750/diigo-mode-emploi-pour-debutants/ ; Présentation de Diigo http://wiki-urfist.unice.fr/wiki_urfist/index.php/M%C3%A9moriser_et_partager_ses_lectures_d%27articles_avec_Diigo" ressource_analogue = "">
		<type nom = "Diffusion/Plateforme de curation" />
		<profil nom = "Enseignant" />
		<profil nom = "Concepteur" />
		<profil nom = "Tuteur" />
		<profil nom = "Gestionnaire" />
	</ressource>
